#!/usr/bin/env python
## Copyright (c) 2021, Alliance for Open Media. All rights reserved
##
## This source code is subject to the terms of the BSD 3-Clause Clear License and the
## Alliance for Open Media Patent License 1.0. If the BSD 3-Clause Clear License was
## not distributed with this source code in the LICENSE file, you can obtain it
## at aomedia.org/license/software-license/bsd-3-c-c/.  If the Alliance for Open Media Patent
## License 1.0 was not distributed with this source code in the PATENTS file, you
## can obtain it at aomedia.org/license/patent-license/.
##
"""
Standalone runner for the perceptual quality metrics (LPIPS, DISTS, ColorVideoVDP).

This is invoked as a subprocess by CalcPerceptualMetrics.py rather than being
imported, for two reasons:

  1. It is the only part of the framework that needs torch. Keeping it in a
     separate process means a normal CTC run never imports torch, and the
     perceptual extras stay optional.
  2. The framework dispatches work to a compute cluster by writing shell
     commands into per-job .sh scripts (see Utils.ExecuteCmd). Only commands
     that go through ExecuteCmd reach the cluster; in-process Python would run
     on the submitting host instead.

Usage:
    python PerceptualMetricsRunner.py --ref orig.y4m --dist recon.y4m \
        --metrics LPIPS,DISTS,CVVDP --frame-step 1 --device auto \
        --cvvdp-display standard_fhd --out <path>/clip_perceptual.json
"""
__author__ = "maggie.sun@intel.com, ryanlei@meta.com"

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile

import numpy as np

from Utils import DecodeY4MToRGB, GetY4MInfo, ToUnitFloat

# All metrics consume display-encoded RGB in [0,1]. For ColorVideoVDP this is
# required rather than incidental: video_source_array is documented as taking
# "display-encoded (gamma-encoded) content that will be processed by a display
# model to produce linear absolute luminance", so the EOTF is applied by the
# --display model, not by us. Feeding absolute luminance here would be wrong.
SUPPORTED_METRICS = ["LPIPS", "DISTS", "CVVDP"]

# Metrics where a lower score means better quality. Used to keep BD-rate signs
# consistent downstream; recorded in the JSON so the consumer need not hardcode it.
LOWER_IS_BETTER = {"LPIPS": True, "DISTS": True, "CVVDP": False}


class RunnerError(Exception):
    """Fatal, user-actionable error. Reported without a traceback."""


######################################
# y4m inspection and RGB conversion
#
# The heavy lifting lives in Utils (GetY4MInfo, DecodeY4MToRGB, ToUnitFloat)
# so the framework has one y4m -> RGB path rather than two.
######################################
def probe_y4m(path):
    """Utils.GetY4MInfo with runner-friendly error reporting."""
    if not os.path.exists(path):
        raise RunnerError("input file not found: %s" % path)
    with open(path, "rb") as f:
        magic = f.readline(16).decode("ascii", errors="replace")
    if not magic.startswith("YUV4MPEG2"):
        raise RunnerError("not a y4m file (bad magic): %s" % path)
    return GetY4MInfo(path)


def resolve_in_range(info, default_range, src):
    """Colour range for the conversion: the file's tag wins over the default.

    y4m may carry XCOLORRANGE=FULL/LIMITED. Files generated by
    `ffmpeg ... -color_range pc` are tagged FULL; standard CTC sequences are
    usually untagged, so the configured default applies.
    """
    tagged = info.get("color_range")
    if tagged:
        return tagged, "XCOLORRANGE tag"
    return default_range, "default (%s is untagged)" % os.path.basename(src)


######################################
# LPIPS / DISTS
######################################
def run_lpips_dists(metrics, ref_mm, dist_mm, frame_indices, device, lpips_net):
    """Per-frame LPIPS/DISTS, averaged over the evaluated frames.

    Returns {metric: {"aggregate": float, "per_frame": {idx: value}, "lower_better": bool}}
    """
    import torch
    import pyiqa

    handles = {}
    for name in metrics:
        # pyiqa names are lowercase; 'lpips' honours the net_type argument.
        if name == "LPIPS":
            handles[name] = pyiqa.create_metric("lpips", device=device, net=lpips_net)
        else:
            handles[name] = pyiqa.create_metric("dists", device=device)

    out = {}
    for name, handle in handles.items():
        # pyiqa exposes polarity per metric; prefer it over our own table so a
        # package-side change cannot silently invert a BD-rate.
        lower = bool(getattr(handle, "lower_better", LOWER_IS_BETTER[name]))
        out[name] = {"per_frame": {}, "lower_better": lower}

    with torch.no_grad():
        for idx in frame_indices:
            ref = ToUnitFloat(ref_mm[idx]).transpose(2, 0, 1)[None, ...]
            dis = ToUnitFloat(dist_mm[idx]).transpose(2, 0, 1)[None, ...]
            ref_t = torch.from_numpy(ref).to(device)
            dis_t = torch.from_numpy(dis).to(device)
            for name, handle in handles.items():
                # pyiqa convention is (distorted, reference).
                val = float(handle(dis_t, ref_t).item())
                out[name]["per_frame"][int(idx)] = val

    for name in out:
        vals = list(out[name]["per_frame"].values())
        out[name]["aggregate"] = float(np.mean(vals)) if vals else float("nan")
    return out


######################################
# ColorVideoVDP
######################################
class _MemmapVideoSource(object):
    """Feeds ColorVideoVDP from our memmapped RGB frames.

    Subclasses cvvdp's display-model video source so the chosen --display
    preset still applies its EOTF and photometry; we only replace where the
    frames come from, so the metric sees exactly the same pixels as LPIPS/DISTS.
    """

    def __new__(cls, *args, **kwargs):
        from pycvvdp.video_source import video_source_dm

        # Built dynamically because the base class lives in an optional package.
        if not hasattr(cls, "_specialised"):
            cls._specialised = type("MemmapVideoSource", (video_source_dm,), dict(
                __init__=cls._init,
                get_frames_per_second=cls._fps,
                get_video_size=cls._size,
                get_test_frame=cls._test_frame,
                get_reference_frame=cls._ref_frame,
            ))
        return cls._specialised(*args, **kwargs)

    @staticmethod
    def _init(self, test_mm, ref_mm, fps, display_photometry):
        from pycvvdp.video_source import video_source_dm

        video_source_dm.__init__(self, display_photometry=display_photometry)
        self.test_mm = test_mm
        self.ref_mm = ref_mm
        self.fps = fps

    @staticmethod
    def _fps(self):
        return self.fps

    @staticmethod
    def _size(self):
        return (self.test_mm.shape[1], self.test_mm.shape[2], self.test_mm.shape[0])

    @staticmethod
    def _frame(self, mm, frame, device, colorspace):
        import torch

        # BCFHW, display-encoded, [0,1]; the display model converts to cd/m^2.
        arr = ToUnitFloat(mm[frame])
        t = torch.from_numpy(arr.transpose(2, 0, 1)[None, :, None, :, :]).to(device)
        return self.apply_dm_and_color_transform(t, colorspace)

    @staticmethod
    def _test_frame(self, frame, device, colorspace):
        return _MemmapVideoSource._frame(self, self.test_mm, frame, device, colorspace)

    @staticmethod
    def _ref_frame(self, frame, device, colorspace):
        return _MemmapVideoSource._frame(self, self.ref_mm, frame, device, colorspace)


def run_cvvdp(ref_mm, dist_mm, fps, device, display):
    """Aggregate JOD plus a per-frame JOD series.

    cvvdp pools Q_per_ch over spatial bands, then channels, then frames. We
    reuse the metric's own pooling for the first two and stop before the frame
    pooling, which yields a per-frame JOD in the same units.

    The aggregate is an Lp norm over frames, NOT an average, so the per-frame
    series will not have the aggregate as its mean.
    """
    import torch
    import pycvvdp

    metric = pycvvdp.cvvdp(display_name=display, device=torch.device(device), quiet=True)
    vs = _MemmapVideoSource(dist_mm, ref_mm, fps, metric.display_photometry)
    jod, stats = metric.predict_video_source(vs)

    per_frame = []
    try:
        Q_per_ch = torch.as_tensor(stats["Q_per_ch"], device=metric.device)
        no_channels, no_bands = Q_per_ch.shape[1], Q_per_ch.shape[3]

        per_ch_w = metric.get_ch_weights(no_channels)
        per_sband_w = torch.ones((1, no_channels, 1, no_bands),
                                 dtype=torch.float32, device=metric.device)
        per_sband_w[:, :, 0, -1] = metric.baseband_weight[0:no_channels]

        # Same two pooling steps as do_pooling_and_jods, minus the frame pooling.
        Q_sc = metric.lp_norm(Q_per_ch * per_ch_w * per_sband_w,
                              metric.beta_sch, dim=3, normalize=False)
        Q_tc = metric.lp_norm(Q_sc, metric.beta_tch, dim=1, normalize=False)
        per_frame = [float(v) for v in metric.met2jod(Q_tc.squeeze()).flatten().tolist()]
    except Exception as e:  # noqa: BLE001 - per-frame is best-effort
        sys.stderr.write("warning: could not derive per-frame JOD: %s\n" % e)

    return {
        "aggregate": float(jod),
        "per_frame": {i: v for i, v in enumerate(per_frame)},
        "lower_better": False,
        "signature": metric.short_name() if hasattr(metric, "short_name") else "",
    }


######################################
# main
######################################
def pick_device(requested):
    try:
        import torch
    except ImportError:
        raise RunnerError(
            "torch is not installed. The perceptual metrics need the optional "
            "extras:\n    pip install -r requirements-perceptual.txt"
        )
    if requested != "auto":
        return requested
    if torch.cuda.is_available():
        return "cuda"
    if hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
        return "mps"
    return "cpu"


def package_versions(metrics):
    versions = {}
    try:
        import torch
        versions["torch"] = torch.__version__
    except ImportError:
        pass
    if {"LPIPS", "DISTS"} & set(metrics):
        try:
            import pyiqa
            versions["pyiqa"] = getattr(pyiqa, "__version__", "unknown")
        except ImportError:
            raise RunnerError(
                "pyiqa is not installed but LPIPS/DISTS were requested.\n"
                "    pip install -r requirements-perceptual.txt"
            )
    if "CVVDP" in metrics:
        try:
            import pycvvdp
            versions["cvvdp"] = getattr(pycvvdp, "__version__", "unknown")
        except ImportError:
            raise RunnerError(
                "cvvdp is not installed but CVVDP was requested.\n"
                "    pip install -r requirements-perceptual.txt"
            )
    return versions


def ParseArguments(raw_args):
    parser = argparse.ArgumentParser(
        prog="PerceptualMetricsRunner.py", usage="%(prog)s [options]",
        description="Compute LPIPS / DISTS / ColorVideoVDP for a y4m pair.",
    )
    parser.add_argument("--ref", dest="Ref", type=str, required=True,
                        help="reference (original) y4m file")
    parser.add_argument("--dist", dest="Dist", type=str, required=True,
                        help="distorted (reconstructed) y4m file")
    parser.add_argument("--out", dest="Out", type=str, required=True,
                        help="output JSON log path")
    parser.add_argument("--metrics", dest="Metrics", type=str, default="LPIPS,DISTS,CVVDP",
                        help="comma separated subset of LPIPS,DISTS,CVVDP")
    parser.add_argument("--frame-step", dest="FrameStep", type=int, default=1,
                        help="evaluate every Nth frame (1 = every frame)")
    parser.add_argument("--device", dest="Device", type=str, default="auto",
                        help="auto, cpu, cuda, cuda:N or mps")
    parser.add_argument("--cvvdp-display", dest="CVVDPDisplay", type=str,
                        default="standard_fhd", help="ColorVideoVDP display preset")
    parser.add_argument("--lpips-net", dest="LpipsNet", type=str, default="alex",
                        choices=["alex", "vgg", "squeeze"],
                        help="LPIPS backbone; alex gives the best forward scores")
    parser.add_argument("--hdr", dest="HDR", action="store_true",
                        help="treat input as HDR: use --hdr-matrix and an HDR "
                             "ColorVideoVDP display preset")
    parser.add_argument("--matrix", dest="Matrix", type=str, default="bt709",
                        help="YUV->RGB matrix for SDR input (bt709, bt601, ...)")
    parser.add_argument("--hdr-matrix", dest="HDRMatrix", type=str,
                        default="bt2020nc",
                        help="YUV->RGB matrix for HDR input")
    parser.add_argument("--in-range", dest="InRange", type=str, default="pc",
                        choices=["tv", "pc"],
                        help="input colour range used when the y4m carries no "
                             "XCOLORRANGE tag; a tagged file overrides this "
                             "(default pc = full range)")
    parser.add_argument("--ffmpeg", dest="FFmpeg", type=str, default="ffmpeg",
                        help="path to the ffmpeg binary")
    return parser.parse_args(raw_args[1:])


def main(raw_args):
    args = ParseArguments(raw_args)

    metrics = [m.strip().upper() for m in args.Metrics.split(",") if m.strip()]
    unknown = [m for m in metrics if m not in SUPPORTED_METRICS]
    if unknown:
        raise RunnerError("unknown metric(s): %s (supported: %s)"
                          % (", ".join(unknown), ", ".join(SUPPORTED_METRICS)))
    if not metrics:
        raise RunnerError("no metrics requested")
    if args.FrameStep < 1:
        raise RunnerError("--frame-step must be >= 1")
    # The framework resolves executables against its bin/ directory, but ffmpeg
    # is very often only on PATH. Fall back rather than failing, and say so.
    ffmpeg = args.FFmpeg
    if shutil.which(ffmpeg) is None and not os.path.exists(ffmpeg):
        fallback = shutil.which("ffmpeg")
        if fallback is None:
            raise RunnerError(
                "ffmpeg not found at %s and not on PATH. Put it in the bin/ "
                "directory, set executables.ffmpeg in config.yaml to an "
                "absolute path, or install ffmpeg." % ffmpeg
            )
        sys.stderr.write(
            "note: %s not found, using %s from PATH\n" % (ffmpeg, fallback))
        ffmpeg = fallback

    device = pick_device(args.Device)
    versions = package_versions(metrics)

    ref_info = probe_y4m(args.Ref)
    dist_info = probe_y4m(args.Dist)
    for key in ("width", "height"):
        if ref_info[key] != dist_info[key]:
            raise RunnerError(
                "reference and distorted differ in %s (%s vs %s); the perceptual "
                "metrics need matching geometry"
                % (key, ref_info[key], dist_info[key])
            )

    matrix = args.HDRMatrix if args.HDR else args.Matrix
    ref_range, ref_why = resolve_in_range(ref_info, args.InRange, args.Ref)
    dist_range, dist_why = resolve_in_range(dist_info, args.InRange, args.Dist)
    if ref_range != dist_range:
        sys.stderr.write(
            "warning: reference is %s range (%s) but distorted is %s (%s); "
            "converting each per its own tag\n"
            % (ref_range, ref_why, dist_range, dist_why))

    tmpdir = tempfile.mkdtemp(prefix="perceptual_")
    try:
        ref_mm, ref_cmd, ref_n = DecodeY4MToRGB(
            ffmpeg, args.Ref, ref_info, matrix, ref_range, tmpdir, "ref")
        dist_mm, dist_cmd, dist_n = DecodeY4MToRGB(
            ffmpeg, args.Dist, dist_info, matrix, dist_range, tmpdir, "dist")

        n_frames = min(ref_n, dist_n)
        if n_frames == 0:
            raise RunnerError("no frames decoded")
        if ref_n != dist_n:
            sys.stderr.write(
                "warning: frame count differs (ref %d, dist %d); using %d\n"
                % (ref_n, dist_n, n_frames))

        frame_indices = list(range(0, n_frames, args.FrameStep))

        results = {}
        image_metrics = [m for m in metrics if m in ("LPIPS", "DISTS")]
        if image_metrics:
            results.update(run_lpips_dists(
                image_metrics, ref_mm, dist_mm, frame_indices, device, args.LpipsNet))

        if "CVVDP" in metrics:
            # ColorVideoVDP models motion, so it always sees the full sequence;
            # frame_step would corrupt its temporal filter.
            if args.FrameStep != 1:
                sys.stderr.write(
                    "note: --frame-step is ignored for CVVDP, which needs "
                    "contiguous frames for its temporal model\n")
            results["CVVDP"] = run_cvvdp(
                ref_mm[:n_frames], dist_mm[:n_frames],
                ref_info["fps"], device, args.CVVDPDisplay)

        payload = {
            "ref": os.path.abspath(args.Ref),
            "dist": os.path.abspath(args.Dist),
            "n_frames": n_frames,
            "frame_step": args.FrameStep,
            "device": device,
            "hdr": bool(args.HDR),
            "cvvdp_display": args.CVVDPDisplay if "CVVDP" in metrics else "",
            "source": ref_info,
            "color_matrix": matrix,
            "in_range_ref": "%s (%s)" % (ref_range, ref_why),
            "in_range_dist": "%s (%s)" % (dist_range, dist_why),
            "ffmpeg_ref": ref_cmd,
            "ffmpeg_dist": dist_cmd,
            "versions": versions,
            "metrics": results,
        }

        os.makedirs(os.path.dirname(os.path.abspath(args.Out)), exist_ok=True)
        with open(args.Out, "w") as f:
            json.dump(payload, f, indent=2, sort_keys=True)
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv))
    except RunnerError as e:
        sys.stderr.write("PerceptualMetricsRunner: %s\n" % e)
        sys.exit(1)
