stages:
  - check
  - build
  - test
  - report

image: registry.gitlab.com/aomediacodec/aom-testing/ubuntu2404:20250715040929

default:
  tags:
    - docker-x86_64

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_COMMIT_BRANCH'
      when: never

# Fetch the test data later needed for the unit test jobs
Test Data:
  stage: check
  interruptible: true
  variables:
    LIBAOM_TEST_DATA_PATH: ${CI_PROJECT_DIR}/libaom-test-data
  script:
    # CMake 4.0.0 removed compatibility with CMake < 3.5. Add
    # -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
    - cmake -B aom_testdata -GNinja -DCMAKE_POLICY_VERSION_MINIMUM=3.5
    - cmake --build aom_testdata --target testdata
  artifacts:
    expire_in: 1 day
    paths:
      - ${CI_PROJECT_DIR}/libaom-test-data

# Simple x86_64 Linux build
Linux Nightly Build:
  stage: build
  interruptible: true
  # CMake 4.0.0 removed compatibility with CMake < 3.5. Add
  # -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
  variables:
    CMAKE_FLAGS: >-
      -DCMAKE_POLICY_VERSION_MINIMUM=3.5
      -DCMAKE_BUILD_TYPE=RelWithDebInfo
      -DAOM_EXTRA_C_FLAGS="--coverage"
      -DAOM_EXTRA_CXX_FLAGS="--coverage"
      -DAOM_EXTRA_EXE_LINKER_FLAGS="--coverage"
  script:
    - 'echo "CMake Flags: $CMAKE_FLAGS"'
    - cmake -B "aom_nightly_build" -GNinja $CMAKE_FLAGS
    - cmake --build "aom_nightly_build" --target aomenc
    - cmake --build "aom_nightly_build" --target test_libaom
  needs: []
  artifacts:
    expire_in: 1 day
    paths:
      - 'aom_nightly_build/aomenc'
      - 'aom_nightly_build/test_libaom'
      - 'aom_nightly_build/**/*.gcno'
      - 'aom_nightly_build/**/*.[hc]'
      - 'aom_nightly_build/**/*.[hc]pp'
      - 'aom_nightly_build/**/*.cc'
      - 'aom_nightly_build/**/*.inc'

# Full unit tests run (with coverage report)
Linux All Unit Test:
  stage: test
  interruptible: true
  parallel: 24
  variables:
    LIBAOM_TEST_DATA_PATH: ${CI_PROJECT_DIR}/libaom-test-data
    GTEST_TOTAL_SHARDS: ${CI_NODE_TOTAL}
    GTEST_OUTPUT: "xml:report.xml"
  before_script:
    - export GTEST_SHARD_INDEX=$((CI_NODE_INDEX - 1))
  script:
    - cd aom_nightly_build
    - ./test_libaom --gtest_filter=-*Large*
    # Ignore parse errors due to a bug in `gcovr 7.0`:
    # https://github.com/gcovr/gcovr/issues/882
    # Ignore errors about 'no_working_dir_found' because
    # tarballs for third_party code (e.g. tensorflow and dependencies) are NOT
    # extracted here and so the source files from those are NOT available.
    - >-
      gcovr
      --gcov-ignore-parse-errors
      --gcov-ignore-errors=no_working_dir_found
      --gcov-executable gcov-14
      --exclude ../third_party --exclude _deps --exclude abseil-cpp --exclude
      benchmark --exclude cpuinfo --exclude eigen --exclude farmhash --exclude
      fft2d --exclude flatbuffers --exclude flatbuffers-flatc --exclude fp16
      --exclude FP16 --exclude FXdiv --exclude psimd  --exclude ml_dtypes
      --exclude neon2sse  --exclude protobuf --exclude pthreadpool --exclude
      pthreadpool-source --exclude ruy --exclude xnnpack --exclude XNNPACK
      --exclude gemmlowp  --exclude googletest
      --exclude-directories "third_party"
      --exclude-directories "aom_nightly_build/third_party" 
      --json -o "coverage_${CI_NODE_INDEX}.json"
      -r ../ . >  "coverage_${CI_NODE_INDEX}.log" 2>&1
  needs:
    - 'Test Data'
    - 'Linux Nightly Build'
  artifacts:
    when: always
    reports:
      junit: ./aom_nightly_build/report.xml
    paths:
      - aom_nightly_build/coverage_*.json
      - aom_nightly_build/coverage_*.log

# Produce actual coverage report from the
# "Linux All Unit Test" job that ran in the
# test stage before.
Coverage Report:
  stage: report
  interruptible: true
  script:
    - mkdir -p coverage-html
    - cd aom_nightly_build
    - >-
      gcovr
      --gcov-executable gcov-14
      --add-tracefile "coverage_*.json"
      --exclude ../third_party --exclude _deps --exclude abseil-cpp --exclude
      benchmark --exclude cpuinfo --exclude eigen --exclude farmhash --exclude
      fft2d --exclude flatbuffers --exclude flatbuffers-flatc --exclude fp16
      --exclude FP16 --exclude FXdiv --exclude psimd  --exclude ml_dtypes
      --exclude neon2sse  --exclude protobuf --exclude pthreadpool --exclude
      pthreadpool-source --exclude ruy --exclude xnnpack --exclude XNNPACK
      --exclude gemmlowp  --exclude googletest
      --xml ../coverage.xml
      --html --html-details ../coverage-html/coverage.html
      --print-summary
      -r ../ .
  artifacts:
    paths:
      - coverage-html